spring:
  application:
    name: backend

webrtc:
  turn:
    ip: "15.165.2.31"
    username: "demo"
    password: "Str0ngPass!"
    port: 3478

passkey:                            #로컬로 사용할 때
  rpId: "15.165.2.31"               #"localhost"
  origin: "http://15.165.2.31:3000" #"http://localhost:3000"