spring:
  application:
    name: backend

  datasource:
    url: "jdbc:mariadb://gamejigi-mariadb.cr686kqo4jsh.ap-northeast-2.rds.amazonaws.com:3306/airlock?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: "admin"
    password: "Qwer1234!"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# WebRTC TURN/STUN 서버 설정
webrtc:
  turn:
    ip: "43.202.212.164"   # 새 Elastic IP 지정
    username: "demo"
    password: "Str0ngPass!" # test deploy
    port: 3478

# FIDO / Passkey 설정
passkey:
  rpId: "43.202.212.164"
  origin: "http://43.202.212.164:3000/"
