spring:
  application:
    name: backend

webrtc:
  turn:
    ip: "43.202.212.164"
    username: "demo"
    password: "Str0ngPass!"
    port: 3478

#passkey:
#  rpId: "43.202.212.164"
#  origin: "http://43.202.212.164:3000"

passkey:
  rpId: localhost
  origin: http://localhost:3000