spring:
  application:
    name: backend

  datasource:
    url: "jdbc:mariadb://gamejigi-mariadb.cr686kqo4jsh.ap-northeast-2.rds.amazonaws.com:3306/airlock?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: "admin"
    password: "Qwer1234!"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

webrtc:
  turn:
    ip: "15.165.2.31"
    username: "demo"
    password: "Str0ngPass!"
    port: 3478
