spring:
  application:
    name: backend

# WebRTC TURN 서버 설정
webrtc:
  turn:
    ip: "<turn_ip>"
    username: "<turn_username>"
    password: "<turn_password>"
    port: 3478

# WebAuthn / Passkey 설정
passkey:                              #서버에서 사용할 때
  rpId: "localhost"                   #15.165.2.31
  origin: "http://localhost:3000"     #http://15.165.2.31:3000